### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by JonathanPitre** [nerdunit/androidsideloader#26]
**Describe the bug**
The error described bellow after launching the app, If I hit continue it work as expected. The error is more of an annoyance than anything else.
[adb.log](https://github.com/nerdunit/androidsideloader/files/6216188/adb.log)

**To Reproduce**
1. Launch the application
2. See error
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at AndroidSideloader.Form1.GetFullPath(String fileName)
   at AndroidSideloader.Form1.ExistsOnPath(String fileName)
   at AndroidSideloader.Form1.HasDependencies()
   at AndroidSideloader.Form1.<Form1_Load>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
AndroidSideloader
    Assembly Version: 1.13.0.0
    Win32 Version: 1.13.0.0
    CodeBase: file:///C:/Users/JakeLD/Documents/VRP%20Essentials/Rookie's%20Sideloader/AndroidSideloader%20v1.17SU1.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4320.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SergeUtils
    Assembly Version: 1.0.0.0
    Win32 Version: 1.13.0.0
    CodeBase: file:///C:/Users/JakeLD/Documents/VRP%20Essentials/Rookie's%20Sideloader/AndroidSideloader%20v1.17SU1.exe
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Expected behavior**
Error appears when the application is launched

**Screenshots**
![Illegal characters in path](https://user-images.githubusercontent.com/15003329/112730843-31a0d180-8f0a-11eb-9a7e-01aee42610de.png)

**Environment (please complete the following information):**
- Debuglog.txt file from the sideloader folder
[debuglog.txt](https://github.com/nerdunit/androidsideloader/files/6216194/debuglog.txt)
- adb.log file from %USERNAME%\AppData\Local\Temp
[adb.log](https://github.com/nerdunit/androidsideloader/files/6216189/adb.log)
- OS: Windows 10 build 19041.867
- Version: 1.17SU1

**Comment by nerdunit** [comment]
Please give the full path of where is sideloader located and also crashlog.txt if you have one

**Comment by nerdunit** [comment]
Closing until you respond...
